networks:
  deploy-dev:
    driver: bridge
services:
  order:
    container_name: order-service
    image: order
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8084
    ports:
      - "8084:8084"
    networks:
      - deploy-dev
    depends_on:
      - order-db
  order-db:
    container_name: order-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
      PGPORT: 5435
    ports:
      - "5435:5435"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - deploy-dev
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - .rabbit-data:/var/lib/rabbitmq
volumes:
  postgres-data:
  rabbit-data:
